// Auto-generated members data for Copa LAWD Sticker Album
const MEMBROS = [
  {
    "id": 1,
    "category": "membro",
    "name": "Gyovani Santos",
    "fullName": "Gyovani Yuri Souza Santos",
    "email": "gyovani.santos@dcomp.ufs.br",
    "phone": "79988697393",
    "birthday": "March 19, 2025",
    "status": "membro efetivo",
    "techs": [
      "CAD",
      "Redes"
    ],
    "areasOfActivity": "Eventos",
    "interests": "Desenvolvimento web, Redes",
    "projects": "WebGarden (https://app.notion.com/p/WebGarden-250412c2ca314f0d8e12fd4defd57726?pvs=21), FORPROEX (https://app.notion.com/p/FORPROEX-2799c7d7a0e94718bd2f1ec2bd2a5c98?pvs=21), Pseudo-Holograma (https://app.notion.com/p/Pseudo-Holograma-0ab1763dbcbc467d9cc5fa13910cb1e8?pvs=21)",
    "image": "Membros/Gyovani Santos/Gyovani.jpeg",
    "isRectangular": false
  },
  {
    "id": 2,
    "category": "membro",
    "name": "Jessica Viana",
    "fullName": "Jéssica Carvalho Viana",
    "email": "v.jessi.carvalho@gmail.com",
    "phone": "79999103379",
    "birthday": "August 7, 2025",
    "status": "membro efetivo",
    "techs": [
      "Backend",
      "Design",
      "FrontEnd"
    ],
    "areasOfActivity": "Ensino",
    "interests": "Eventos",
    "projects": "Site do Processo Seletivo LAWD (https://app.notion.com/p/Site-do-Processo-Seletivo-LAWD-e6299717a4994b1d96bc4177a8e3c788?pvs=21), WebGarden (https://app.notion.com/p/WebGarden-250412c2ca314f0d8e12fd4defd57726?pvs=21)",
    "image": "Membros/Jessica Viana/Untitled.png",
    "isRectangular": false
  },
  {
    "id": 3,
    "category": "membro",
    "name": "Wanessa Santos",
    "fullName": "Wanessa Silva Santos",
    "email": "wanessasantos024@gmail.com",
    "phone": "79996860241",
    "birthday": "April 27, 2025",
    "status": "diretor",
    "techs": [
      "Adm",
      "Java"
    ],
    "areasOfActivity": "RH",
    "interests": "Projetos, RH",
    "projects": "Untitled (https://app.notion.com/p/c0f5fc1ef7344bb5807570dd785c2e27?pvs=21), Calicomp (https://app.notion.com/p/Calicomp-e28a2450d4a14c4f8dd2e3ab0ecbd264?pvs=21)",
    "image": "Membros/Wanessa Santos/IMG-20240920-WA0110.webp",
    "isRectangular": false
  },
  {
    "id": 4,
    "category": "membro",
    "name": "João Felipe Quentino",
    "fullName": "João Felipe Quentino",
    "email": "felipequentino22@gmail.com",
    "phone": "82 981166166",
    "birthday": "April 6, 2025",
    "status": "membro efetivo",
    "techs": [
      "Automação",
      "IA",
      "Machine Learning",
      "Python"
    ],
    "areasOfActivity": "Ensino",
    "interests": "IA, Pesquisa",
    "projects": "Modelo de ML de Notas (https://app.notion.com/p/Modelo-de-ML-de-Notas-d42cf958ce674bf38ccec174d2f729f8?pvs=21), Chatbot do Processo Seletivo (https://app.notion.com/p/Chatbot-do-Processo-Seletivo-5a7b5a7d29ba4d54a68cd27026230d6a?pvs=21)",
    "image": "Membros/João Felipe Quentino/Joo_F._Quentino_-_Diretor_de_Pesquisa.jpg",
    "isRectangular": false
  },
  {
    "id": 5,
    "category": "membro",
    "name": "Maria Luiza",
    "fullName": "Maria Luiza Ferreira Matos",
    "email": "malufmatos22@gmail.com",
    "phone": "79981452229",
    "birthday": "July 22, 2025",
    "status": "membro efetivo",
    "techs": [
      "Backend",
      "Design",
      "FrontEnd"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Marketing, Pesquisa, Projetos",
    "projects": "Site do Processo Seletivo LAWD (https://app.notion.com/p/Site-do-Processo-Seletivo-LAWD-e6299717a4994b1d96bc4177a8e3c788?pvs=21), FORPROEX (https://app.notion.com/p/FORPROEX-2799c7d7a0e94718bd2f1ec2bd2a5c98?pvs=21), Divided Space (https://app.notion.com/p/Divided-Space-4935a47877114b3984832b52153bbb66?pvs=21), Modelo de ML de Notas (https://app.notion.com/p/Modelo-de-ML-de-Notas-d42cf958ce674bf38ccec174d2f729f8?pvs=21)",
    "image": "Membros/Maria Luiza/Untitled.png",
    "isRectangular": false
  },
  {
    "id": 6,
    "category": "membro",
    "name": "Alipio Fernando",
    "fullName": "Alipio Fenando de Paula Pires",
    "email": "alipiofernandopires@gmail.com",
    "phone": "79996768917",
    "birthday": "September 17, 2025",
    "status": "membro efetivo",
    "techs": [],
    "areasOfActivity": "",
    "interests": "Design, Eventos",
    "projects": "Untitled (https://app.notion.com/p/c0f5fc1ef7344bb5807570dd785c2e27?pvs=21), WebGarden (https://app.notion.com/p/WebGarden-250412c2ca314f0d8e12fd4defd57726?pvs=21), FORPROEX (https://app.notion.com/p/FORPROEX-2799c7d7a0e94718bd2f1ec2bd2a5c98?pvs=21), Chatbot do Processo Seletivo (https://app.notion.com/p/Chatbot-do-Processo-Seletivo-5a7b5a7d29ba4d54a68cd27026230d6a?pvs=21)",
    "image": "Membros/Alipio Fernando/Untitled.jpeg",
    "isRectangular": false
  },
  {
    "id": 7,
    "category": "membro",
    "name": "Guilherme Viana",
    "fullName": "Guilherme Lavrador Viana",
    "email": "guilavrador@gmail.com",
    "phone": "73991484896",
    "birthday": "March 4, 2025",
    "status": "diretor",
    "techs": [
      "Arduino",
      "C",
      "FastAPI",
      "Flutter",
      "GIT",
      "Java",
      "Python",
      "Spring Boot",
      "Sql"
    ],
    "areasOfActivity": "Adm",
    "interests": "Administrativa, Desenvolvimento web, Embarcados, Mobile, Projetos",
    "projects": "",
    "image": "Membros/Guilherme Viana/GuilhermeViana.jpeg",
    "isRectangular": false
  },
  {
    "id": 8,
    "category": "membro",
    "name": "Pedro Lucas",
    "fullName": "Pedro Lucas Souza de Novaes",
    "email": "opedro.lucassn@academico.ufs.br",
    "phone": "75991285089",
    "birthday": "September 20, 2025",
    "status": "diretor",
    "techs": [
      "C",
      "CSS",
      "Canva",
      "CapCut",
      "Design",
      "FrontEnd",
      "HTML",
      "JavaScript",
      "Photoshop",
      "Python"
    ],
    "areasOfActivity": "Marketing",
    "interests": "Desenvolvimento web, Marketing",
    "projects": "",
    "image": "Membros/Pedro Souza/PedroLucas.webp",
    "isRectangular": false
  },
  {
    "id": 9,
    "category": "membro",
    "name": "Wesley Góis",
    "fullName": "Wesley Kauanderlon de Carvalho Góis",
    "email": "kauanderlon095@gmail.com",
    "phone": "(79) 99641-7259",
    "birthday": "July 10, 2025",
    "status": "diretor",
    "techs": [
      "CSS",
      "HTML",
      "Java",
      "Python",
      "Sql"
    ],
    "areasOfActivity": "CORP, Secr.Geral",
    "interests": "Design, Marketing, Metodologias Ágeis",
    "projects": "",
    "image": "Membros/Wesley Góis/WesleyKauanderlon.jpg",
    "isRectangular": false
  },
  {
    "id": 10,
    "category": "membro",
    "name": "Enzo Emanuel",
    "fullName": "Enzo Emanuel Maia Costa",
    "email": "enzoemcosta@academico.ufs.br",
    "phone": "(88)996880539",
    "birthday": "March 6, 2025",
    "status": "membro efetivo",
    "techs": [
      "CSS",
      "HTML",
      "JavaScript"
    ],
    "areasOfActivity": "Marketing",
    "interests": "Desenvolvimento web, Marketing",
    "projects": "",
    "image": "Membros/Enzo Emanuel/EnzoMaia.jpg",
    "isRectangular": false
  },
  {
    "id": 11,
    "category": "membro",
    "name": "Dimitri Martins",
    "fullName": "Dimitri Martins Oliveira",
    "email": "dimitrimartins070@gmail.com",
    "phone": "75997079796",
    "birthday": "September 14, 2005",
    "status": "membro efetivo",
    "techs": [
      "CSS",
      "HTML",
      "JavaScript"
    ],
    "areasOfActivity": "Ensino",
    "interests": "Machine Learning",
    "projects": "",
    "image": "Membros/Dimitri Martins/DimitriMartins2.jpg",
    "isRectangular": false
  },
  {
    "id": 12,
    "category": "membro",
    "name": "Bruno Saint Clair",
    "fullName": "Bruno Saint Clair",
    "email": "brunosaint@academico.ufs.br / brunosaint.dev@gmail.com",
    "phone": "79 996870894",
    "birthday": "June 18, 2025",
    "status": "diretor",
    "techs": [
      "Django Rest Framework",
      "Python",
      "Spring Boot"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Backend, Ciência de Dados",
    "projects": "",
    "image": "Membros/Bruno Saint Clair/BrunoSaintClair.jpg",
    "isRectangular": false
  },
  {
    "id": 13,
    "category": "membro",
    "name": "Breno Gustavo",
    "fullName": "Breno Gustavo dos Reis Santos",
    "email": "brenogustavo780@gmail.com",
    "phone": "79996576604",
    "birthday": "September 4, 2003",
    "status": "membro efetivo",
    "techs": [
      "Design",
      "Java",
      "PostGreSQL"
    ],
    "areasOfActivity": "Marketing",
    "interests": "Design, Marketing",
    "projects": "",
    "image": "Membros/Breno Gustavo/BrenoGustavo.jpg",
    "isRectangular": false
  },
  {
    "id": 14,
    "category": "membro",
    "name": "André Felipe",
    "fullName": "André Felipe de Santana Conceição",
    "email": "andrefelipesi@academico.ufs.br",
    "phone": "(79) 9 9839-6408",
    "birthday": "April 23, 2025",
    "status": "membro efetivo",
    "techs": [
      "C",
      "CSS",
      "HTML",
      "Java"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Projetos",
    "projects": "",
    "image": "Membros/André Felipe/AndrFelipe.jpg",
    "isRectangular": false
  },
  {
    "id": 15,
    "category": "membro",
    "name": "Pedro Corrêa",
    "fullName": "Pedro Corrêa Castello Branco",
    "email": "pdrocorreak@gmail.com",
    "phone": "79 9 9123-3659",
    "birthday": "November 25, 2004",
    "status": "membro efetivo",
    "techs": [
      "Java",
      "JavaScript",
      "Lua"
    ],
    "areasOfActivity": "Projetos",
    "interests": "",
    "projects": "",
    "image": "Membros/Pedro Corrêa/pedroCorrea_(1).png",
    "isRectangular": false
  },
  {
    "id": 16,
    "category": "membro",
    "name": "Paulo Marques",
    "fullName": "Paulo Marques de Oliveira Silva",
    "email": "paulomarques.comp@gmail.com",
    "phone": "79996273266",
    "birthday": "March 6, 1999",
    "status": "membro efetivo",
    "techs": [
      "React",
      "Tailwind",
      "TypeScript"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Pesquisa, Projetos",
    "projects": "",
    "image": "Membros/Paulo Marques/PauloMarques.jpeg",
    "isRectangular": false
  },
  {
    "id": 17,
    "category": "membro",
    "name": "Luan Meireles",
    "fullName": "Luan Meireles Pinheiro Guimarães",
    "email": "luangmrs@gmail.com",
    "phone": "79 991727001",
    "birthday": "July 28, 2025",
    "status": "diretor",
    "techs": [
      ".NET",
      "C",
      "C#",
      "C++",
      "CSS",
      "HTML",
      "JavaScript"
    ],
    "areasOfActivity": "Eventos",
    "interests": "Desenvolvimento web, Realidade Aumentada/Estendida",
    "projects": "",
    "image": "Membros/Luan Meireles/LuanMeireles.jpg",
    "isRectangular": false
  },
  {
    "id": 18,
    "category": "membro",
    "name": "Irlan Alves",
    "fullName": "Irlan Felipe Alves dos Santos",
    "email": "irlanf06@gmail.com",
    "phone": "79 9 99958-7128",
    "birthday": "June 28, 2025",
    "status": "membro efetivo",
    "techs": [
      "C",
      "CSS",
      "GIT",
      "HTML",
      "JavaScript",
      "Vercel"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Administrativa, Ensino, Projetos",
    "projects": "",
    "image": "Membros/Irlan Alves/IrlanAlves.webp",
    "isRectangular": false
  },
  {
    "id": 19,
    "category": "membro",
    "name": "Lauane Morais",
    "fullName": "Lauane de Morais Araujo",
    "email": "lauanemoraisufs@gmail.com",
    "phone": "79981470682",
    "birthday": "April 14, 2025",
    "status": "vice-presidente",
    "techs": [
      "Python"
    ],
    "areasOfActivity": "CORP",
    "interests": "Eventos, Mini-cursos",
    "projects": "",
    "image": "Membros/Lauane Morais/LauaneMorais.jpg",
    "isRectangular": false
  },
  {
    "id": 20,
    "category": "membro",
    "name": "Gustavo Aragão",
    "fullName": "Gustavo Henrique Aragão Silva",
    "email": "gustavohenriquearagaosilva@gmail.com",
    "phone": "79999485350",
    "birthday": "May 27, 2025",
    "status": "presidente",
    "techs": [
      "Backend",
      "C++",
      "CAD",
      "Eletrônica",
      "FrontEnd",
      "Python",
      "Spring Boot",
      "VueJS"
    ],
    "areasOfActivity": "CORP",
    "interests": "DevOps, Gestão, IA, Pesquisa, RH, Redes",
    "projects": "",
    "image": "Membros/Gustavo Aragão/GustavoHenrique.jpg",
    "isRectangular": false
  },
  {
    "id": 21,
    "category": "membro",
    "name": "Erick Juan",
    "fullName": "Erick Juan Gois Oliveira",
    "email": "erickjuan50@gmail.com",
    "phone": "79991073025",
    "birthday": "September 23, 2025",
    "status": "diretor",
    "techs": [
      "Design",
      "Java",
      "Redes"
    ],
    "areasOfActivity": "Ensino",
    "interests": "Desenvolvimento web, Mini-cursos, Pesquisa",
    "projects": "",
    "image": "Membros/Erick Juan/1000080751.jpg",
    "isRectangular": false
  },
  {
    "id": 22,
    "category": "membro",
    "name": "Gabriel Argôlo",
    "fullName": "Gabriel Argôlo Julião dos Santos",
    "email": "gabriel.argolo@dcomp.ufs.br",
    "phone": "+55 79 98847-2623",
    "birthday": "January 8, 2025",
    "status": "membro efetivo",
    "techs": [
      "CSS",
      "GIT",
      "HTML",
      "JavaScript"
    ],
    "areasOfActivity": "Eventos",
    "interests": "Desenvolvimento web, Metodologias Ágeis, Projetos",
    "projects": "",
    "image": "Membros/Gabriel Argôlo/Gabriel_Arglo.jpg",
    "isRectangular": false
  },
  {
    "id": 23,
    "category": "membro",
    "name": "Giulian Bastos",
    "fullName": "Giulian Fábio Bastos Amorim Lima",
    "email": "giutrum@gmail.com",
    "phone": "75998892472",
    "birthday": "March 23, 2025",
    "status": "membro efetivo",
    "techs": [
      "Bootstrap",
      "CSS",
      "FrontEnd",
      "HTML",
      "JavaScript"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Desenvolvimento web, Mini-cursos, Projetos, Redes",
    "projects": "",
    "image": "Membros/Giulian Bastos/Giulian_Bastos.jpeg",
    "isRectangular": false
  },
  {
    "id": 24,
    "category": "membro",
    "name": "Thayla Figueiredo",
    "fullName": "Thayla Almeida Figueiredo",
    "email": "thayla_a@academico.ufs.br",
    "phone": "74 999303324",
    "birthday": "May 1, 2025",
    "status": "membro efetivo",
    "techs": [
      "C",
      "JavaScript"
    ],
    "areasOfActivity": "Eventos",
    "interests": "Desenvolvimento web, Marketing, Projetos",
    "projects": "",
    "image": "Membros/Thayla Figueiredo/Thayla.jpeg",
    "isRectangular": false
  },
  {
    "id": 25,
    "category": "membro",
    "name": "Daniel Trindade",
    "fullName": "Daniel José Silva Trindade",
    "email": "daniljstri@academico.ufs.br",
    "phone": "79 9 9996 4133",
    "birthday": "May 12, 2025",
    "status": "membro efetivo",
    "techs": [
      "Automação",
      "Django",
      "Pandas",
      "Python"
    ],
    "areasOfActivity": "Adm",
    "interests": "Análise de dados, Automação, Mini-cursos",
    "projects": "Modelo de ML de Notas (https://app.notion.com/p/Modelo-de-ML-de-Notas-d42cf958ce674bf38ccec174d2f729f8?pvs=21), FORPROEX (https://app.notion.com/p/FORPROEX-2799c7d7a0e94718bd2f1ec2bd2a5c98?pvs=21), Chatbot do Processo Seletivo (https://app.notion.com/p/Chatbot-do-Processo-Seletivo-5a7b5a7d29ba4d54a68cd27026230d6a?pvs=21)",
    "image": "Membros/Daniel Trindade/Daniel_Trindade_-_Secretrio_Geral.jpg",
    "isRectangular": false
  },
  {
    "id": 26,
    "category": "membro",
    "name": "Vinícius Morais",
    "fullName": "Vinícius Morais Souza",
    "email": "viniciusms10@academico.ufs.br",
    "phone": "79 9 9895-5983",
    "birthday": "March 24, 2025",
    "status": "membro efetivo",
    "techs": [
      "FrontEnd"
    ],
    "areasOfActivity": "Adm",
    "interests": "Desenvolvimento web",
    "projects": "Divided Space (https://app.notion.com/p/Divided-Space-4935a47877114b3984832b52153bbb66?pvs=21)",
    "image": "Membros/Vinícius Morais/Vincius_-_Diretor_Administrativo.jpg",
    "isRectangular": false
  },
  {
    "id": 27,
    "category": "membro",
    "name": "Gabriel Almeida",
    "fullName": "Gabriel dos Santos Almeida",
    "email": "gabriel.almeida@dcomp.ufs.br",
    "phone": "79988298369",
    "birthday": "February 25, 2025",
    "status": "membro efetivo",
    "techs": [
      "C",
      "Design",
      "Python"
    ],
    "areasOfActivity": "Eventos",
    "interests": "Eventos, Pesquisa, Projetos",
    "projects": "Chatbot do Processo Seletivo (https://app.notion.com/p/Chatbot-do-Processo-Seletivo-5a7b5a7d29ba4d54a68cd27026230d6a?pvs=21), Site do Dcomp (https://app.notion.com/p/Site-do-Dcomp-111b4deeb0024a8c9d7d9a6dd74c6222?pvs=21), FORPROEX (https://app.notion.com/p/FORPROEX-2799c7d7a0e94718bd2f1ec2bd2a5c98?pvs=21)",
    "image": "Membros/Gabriel Almeida/Untitled.jpeg",
    "isRectangular": false
  },
  {
    "id": 28,
    "category": "membro",
    "name": "Guilherme Linard",
    "fullName": "Guilherme Linard Pereira",
    "email": "g_linard@hotmail.com",
    "phone": "79991439000",
    "birthday": "February 21, 2025",
    "status": "membro efetivo",
    "techs": [
      "Dart",
      "Flutter"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Projetos",
    "projects": "Site do Processo Seletivo LAWD (https://app.notion.com/p/Site-do-Processo-Seletivo-LAWD-e6299717a4994b1d96bc4177a8e3c788?pvs=21), Site do Dcomp (https://app.notion.com/p/Site-do-Dcomp-111b4deeb0024a8c9d7d9a6dd74c6222?pvs=21)",
    "image": "Membros/Guilherme Linard/Untitled.jpeg",
    "isRectangular": false
  },
  {
    "id": 29,
    "category": "membro",
    "name": "Davi Bittencourt",
    "fullName": "Davi Bittencourt de Almeida",
    "email": "davi.almeida@dcomp.ufs.br",
    "phone": "79998283662",
    "birthday": "August 19, 2025",
    "status": "membro efetivo",
    "techs": [
      ".NET",
      "Backend",
      "C#",
      "FrontEnd",
      "GIT",
      "Java",
      "JavaScript",
      "NodeJS",
      "React",
      "TypeScript"
    ],
    "areasOfActivity": "Projetos",
    "interests": "Desenvolvimento web, Metodologias Ágeis, Projetos, Redes",
    "projects": "Site do Processo Seletivo LAWD (https://app.notion.com/p/Site-do-Processo-Seletivo-LAWD-e6299717a4994b1d96bc4177a8e3c788?pvs=21), WebGarden (https://app.notion.com/p/WebGarden-250412c2ca314f0d8e12fd4defd57726?pvs=21), FORPROEX (https://app.notion.com/p/FORPROEX-2799c7d7a0e94718bd2f1ec2bd2a5c98?pvs=21)",
    "image": "Membros/Davi Bittencourt/Untitled.jpeg",
    "isRectangular": false
  },
  {
    "id": 30,
    "category": "membro",
    "name": "Álvaro Luís",
    "fullName": "Álvaro Luis Silva Peixoto",
    "email": "alvaroluis871@gmail.com",
    "phone": "75999426014",
    "birthday": "September 26, 2025",
    "status": "membro efetivo",
    "techs": [
      "Backend",
      "FrontEnd",
      "RDBMS"
    ],
    "areasOfActivity": "Ensino",
    "interests": "Projetos",
    "projects": "Site do Processo Seletivo LAWD (https://app.notion.com/p/Site-do-Processo-Seletivo-LAWD-e6299717a4994b1d96bc4177a8e3c788?pvs=21), FORPROEX (https://app.notion.com/p/FORPROEX-2799c7d7a0e94718bd2f1ec2bd2a5c98?pvs=21), Chatbot do Processo Seletivo (https://app.notion.com/p/Chatbot-do-Processo-Seletivo-5a7b5a7d29ba4d54a68cd27026230d6a?pvs=21)",
    "image": "Membros/Álvaro Luís/Untitled.jpeg",
    "isRectangular": false
  },
  {
    "id": 31,
    "category": "membro",
    "name": "Isadora Oliveira",
    "fullName": "Isadora Oliveira Santos",
    "email": "isaa.oliverahta@gmail.com",
    "phone": "(79) 98876-5514",
    "birthday": "September 26, 2005",
    "status": "membro efetivo",
    "techs": [
      "Canva",
      "CapCut",
      "Figma",
      "Illustrator",
      "Photoshop"
    ],
    "areasOfActivity": "Marketing",
    "interests": "Design, Marketing",
    "projects": "",
    "image": "Membros/Isadora Oliveira/IsadoraOliveira.jpg",
    "isRectangular": false
  },
  {
    "id": 32,
    "category": "membro",
    "name": "Irwing Felipe",
    "fullName": "Irwing Felipe Pereira Vieira",
    "email": "irwingfelipe@gmail.com",
    "phone": "74 99969-1267",
    "birthday": "August 8, 2025",
    "status": "membro efetivo",
    "techs": [
      "C",
      "Java",
      "Python"
    ],
    "areasOfActivity": "Ensino",
    "interests": "Desenvolvimento web, Design de Jogos, IA",
    "projects": "",
    "image": "Membros/Irwing Felipe/IrwingFelipe.jpg",
    "isRectangular": false
  },
  {
    "id": 33,
    "category": "membro",
    "name": "Levi Ribeiro",
    "fullName": "Levi Ribeiro Santiago de Mendonça",
    "email": "l3v1.rib@gmail.com",
    "phone": "79999129275",
    "birthday": "April 7, 2003",
    "status": "membro efetivo",
    "techs": [
      "Java",
      "Python",
      "Tailwind"
    ],
    "areasOfActivity": "RH",
    "interests": "Ciência de Dados, Design",
    "projects": "",
    "image": "Membros/Levi Ribeiro/LeviRibeiro.jpeg",
    "isRectangular": false
  },
  {
    "id": 34,
    "category": "evento",
    "name": "Aprovados Ps 2024",
    "fullName": "Aprovados Ps 2024",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/aprovados-ps-2024.png",
    "isRectangular": true
  },
  {
    "id": 35,
    "category": "evento",
    "name": "Expo Comp",
    "fullName": "Expo Comp",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/expo-comp.png",
    "isRectangular": true
  },
  {
    "id": 36,
    "category": "evento",
    "name": "Fusao Vice Presida",
    "fullName": "Fusao Vice Presida",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/fusao-vice-presida.jpeg",
    "isRectangular": true
  },
  {
    "id": 37,
    "category": "evento",
    "name": "LAWD 2 Anos",
    "fullName": "LAWD 2 Anos",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/lawd-2anos.png",
    "isRectangular": true
  },
  {
    "id": 38,
    "category": "evento",
    "name": "LAWD Campus Party",
    "fullName": "LAWD Campus Party",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/lawd-campus-party.png",
    "isRectangular": true
  },
  {
    "id": 39,
    "category": "evento",
    "name": "LAWD Hackaia",
    "fullName": "LAWD Hackaia",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/lawd-hackaia.jpeg",
    "isRectangular": true
  },
  {
    "id": 40,
    "category": "evento",
    "name": "LAWD Semac X",
    "fullName": "LAWD Semac X",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/lawd-semac-X.png",
    "isRectangular": true
  },
  {
    "id": 41,
    "category": "evento",
    "name": "LAWD Semac XI",
    "fullName": "LAWD Semac XI",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/lawd-semac-XI.png",
    "isRectangular": true
  },
  {
    "id": 42,
    "category": "evento",
    "name": "Niver Ano 1",
    "fullName": "Niver Ano 1",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/niver-ano-1.jpeg",
    "isRectangular": true
  },
  {
    "id": 43,
    "category": "evento",
    "name": "Primeira Reuniao Geral",
    "fullName": "Primeira Reuniao Geral",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/primeira-reuniao-geral.jpeg",
    "isRectangular": true
  },
  {
    "id": 44,
    "category": "evento",
    "name": "Root Para LAWD",
    "fullName": "Root Para LAWD",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/root-para-lawd.jpeg",
    "isRectangular": true
  },
  {
    "id": 45,
    "category": "evento",
    "name": "Sim Grade 1.0",
    "fullName": "Sim Grade 1.0",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Evento",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Eventos/sim-grade-1.0.png",
    "isRectangular": true
  },
  {
    "id": 46,
    "category": "lugar",
    "name": "Confra Espetinho Do Ze",
    "fullName": "Confra Espetinho Do Ze",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/confra-espetinho-do-ze.jpeg",
    "isRectangular": true
  },
  {
    "id": 47,
    "category": "lugar",
    "name": "Jardim Novos Membros",
    "fullName": "Jardim Novos Membros",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/jardim-novos-membros.jpeg",
    "isRectangular": true
  },
  {
    "id": 48,
    "category": "lugar",
    "name": "LAWD CCET Fundacao",
    "fullName": "LAWD CCET Fundacao",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/lawd-ccet-fundacao.jpeg",
    "isRectangular": true
  },
  {
    "id": 49,
    "category": "lugar",
    "name": "LAWD Floyd",
    "fullName": "LAWD Floyd",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/lawd-floyd.jpeg",
    "isRectangular": true
  },
  {
    "id": 50,
    "category": "lugar",
    "name": "LAWD MPSE",
    "fullName": "LAWD MPSE",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/lawd-mpse.jpeg",
    "isRectangular": true
  },
  {
    "id": 51,
    "category": "lugar",
    "name": "LAWD Sti",
    "fullName": "LAWD Sti",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/lawd-sti.png",
    "isRectangular": true
  },
  {
    "id": 52,
    "category": "lugar",
    "name": "LAWD UFS BR",
    "fullName": "LAWD UFS BR",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/lawd-ufsbr.jpeg",
    "isRectangular": true
  },
  {
    "id": 53,
    "category": "lugar",
    "name": "Sala CCET",
    "fullName": "Sala CCET",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/sala-ccet.jpeg",
    "isRectangular": true
  },
  {
    "id": 54,
    "category": "lugar",
    "name": "Web Lab",
    "fullName": "Web Lab",
    "email": "",
    "phone": "",
    "birthday": "",
    "status": "Lugar",
    "techs": [],
    "areasOfActivity": "",
    "interests": "",
    "projects": "",
    "image": "Lugares/web-lab.png",
    "isRectangular": true
  }
];
